#! /usr/bin/env python3

import juhrnal
import plot

print('Reading...', end= '', flush= True)
j= juhrnal.Juhrnal()
print('done')

print('Histograms...', end= '', flush= True)
plot.plot_histograms(j)
print('done')
