#! /usr/bin/env python3

import juhrnal
import plot

print('Reading...', end= '', flush= True)
j= juhrnal.Juhrnal()
print('done')

print('Measurement plots...', end= '', flush= True)
plot.plot_measurements(j)
print('done')
