#! /usr/bin/env python3
#
# INPUT FILES
#	sante/SportsHealth-Data.csv
#
# OUTPUT FILES
#	dat/tracker.(steps distance)
#

import re

fin= open('sante/huawei/SportsHealth-Data.csv', 'r')
out_distance= open('dat/tracker.distance', 'w')
out_steps   = open('dat/tracker.steps'   , 'w')

while True:
    line= fin.readline()
    if not line:  break

    m= re.compile('^([0-9][0-9][0-9][0-9*])([0-9][0-9])([0-9][0-9]).*distance"":([0-9]+),.*steps"":([0-9]+)}.*$').match(line)
    if m:
        text_year    = m.group(1)
        text_month   = m.group(2)
        text_day     = m.group(3)
        text_distance= m.group(4)
        text_steps   = m.group(5)

        print(f'{text_year}-{text_month}-{text_day}\t{text_steps}'   , file=out_steps   )
        print(f'{text_year}-{text_month}-{text_day}\t{text_distance}', file=out_distance)

fin.close()
out_distance.close()
out_steps   .close()
